version: "3"

services:
  fuseki:
    image: lyrasis/blazegraph:2.1.5
    container_name: blazegraph
    restart: always
    ports:
      - "8889:8080"
    volumes:
      - blazegraph-data:/var/lib/blazegraph/data
volumes:
  blazegraph-data: